---
- hosts: all
  become: True
  gather_facts: False

  pre_tasks:
    - raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
    - setup: # aka gather_facts

  vars_files:
  #  - ../vars/database_server_vars.yml
  #  - ../vars/database_server_vault.yml

  roles:
    - { role: common }
  #  - { role: dbutils }
  #  - { role: deimosfr.mariadb }
  #  - { role: franklinkim.environment }