pip_package: python3-pip

mysql_user_home: /root
mysql_user_name: root
mysql_user_password: root

mysql_port: "3306"
mysql_bind_address: '0.0.0.0'
mysql_datadir: /var/lib/mysql
mysql_socket: /var/run/mysqld/mysqld.sock
mysql_pid_file: /var/run/mysqld/mysqld.pid

# Databases
mysql_databases:
  - { name: experiment, collation: utf8_general_ci, encoding: utf8 }

# Users
mysql_users:
  - name: experiment
    host: '%'
    password: "{{ experiment_db_password | default('experiment') }}"
    priv: 'experiment.*:ALL'

